### ISSUE TITLE
Line Images not being created for every Image

### ISSUE THREAD

**Issue by jonahkaye** [jpuigcerver/PyLaia#29] opened 2020-08-21 15:44 UTC
Hi! When I run the portion of the script that uses TextFeats to create the line images, it isnt creating Line images for every single Id. When I run the htr-train-ctc I get a slew of warnings because the line images are present for a lot of the Text, which is all correct and present in train_gt.txt. Any suggestions for what might be happening?

**Comment by jonahkaye** [comment] 2020-08-25 14:42
The PylaiaGuide script for colab. When I try to run !pylaia-htr-train-ctc with all the appropriate specifications, I get this error hundreds of times: 
2020-08-21 16:28:44,447 WARNING laia.data.text_image_from_text_table_dataset : No image file was found for image ID "073_031_001.r116", ignoring example.
The problem is that when I do this step earlier on in the script: 
```
for i in *.xml; do
N=`basename $i .xml`
textFeats --cfg <( echo "$textFeats_cfg" ) --outdir ../Lines $i
```
It doesntc create line images for every file.

**Comment by carmocca** [comment] 2020-09-02 16:56
> The PylaiaGuide script for colab.

I am sorry, but we don't support user-made scripts. I do not know what script you are talking about since we do not provide any colab files at the moment. We can help you with a particular issue as long as you can isolate it.

> 2020-08-21 16:28:44,447 WARNING laia.data.text_image_from_text_table_dataset : No image file was found for image ID "073_031_001.r116", ignoring example.

PyLaia outputs that warning because it cant find the image "073_031_001.r116" in `img_dirs` (`pylaia-htr-train-ctc` argument).

> It doesntc create line images for every file.

If `textFeats` is failing to run for some specific images, you should try running it manually on those to see what is the problem.
If the problem is within textFeats, opening an issue in https://github.com/mauvilsa/textfeats may be more appropriate.

Closing this issue since it doesn't seem to be an actual PyLaia problem. Feel free to provide more details if necessary.

**Closed by carmocca** 2020-09-02 16:56 UTC
