### ISSUE TITLE
Hugging Face Hub intergration

### ISSUE THREAD

**Issue by davanstrien** [jpuigcerver/PyLaia#76] opened 2023-12-21 14:29 UTC
It's really great to see so much work going into open-source HTR!  It could be cool to have closer integration with the Hugging Face Hub. I know you are already sharing models there, but having a direct method for downloading and pushing models to the Hub would be super nice and could help increase the usage of open models. 

Happy to offer some guidance on the best approach for doing this if it is of interest 🤗

**Comment by yschneiderTEKLIA** [comment] 2023-12-21 14:51
Hey @davanstrien 

Thanks for reaching out to us. We are definitely interested in this feature and have been trying to find some time to do the integration already. While this won't be in the next release, this is on our roadmap for the future ones.

As the pinned issue says, development is no longer done here but on [GitLab](https://gitlab.teklia.com/atr/pylaia/) instead, as pointed on Hugging Face and in the [documentation](https://atr.pages.teklia.com/pylaia/). So please prefer using the [issue tracker over there](https://gitlab.teklia.com/atr/pylaia/-/issues).

I'm closing this as a dupe of https://gitlab.teklia.com/atr/pylaia/-/issues/29.

**Closed by yschneiderTEKLIA** 2023-12-21 14:51 UTC
